test_that("summary returns the fit settings and per-cluster table", {
  withr::local_seed(123L)
  x <- as.matrix(iris[, -5L])
  cl <- gmeans(x, k_init = 1L, k_max = 5L, level = 0.01)
  res <- summary(cl)
  expect_s3_class(res, "summary.gmeans")
  expect_identical(res$k, nrow(cl$centers))
  expect_identical(res$k_init, 1L)
  expect_identical(res$k_max, 5L)
  expect_identical(res$level, 0.01)
  expect_identical(res$totss, cl$totss)
  expect_named(res$clusters, c("cluster", "size", "withinss", colnames(x)))
  expect_identical(nrow(res$clusters), nrow(cl$centers))
  expect_identical(res$clusters$size, cl$size)
  expect_identical(res$clusters$withinss, cl$withinss)
  expect_identical(unname(as.matrix(res$clusters[, colnames(x)])), unname(cl$centers))
})

test_that("summary names unnamed centers", {
  withr::local_seed(123L)
  cl <- gmeans(unname(as.matrix(iris[, 1:2])))
  expect_named(summary(cl)$clusters, c("cluster", "size", "withinss", "x1", "x2"))
})

test_that("print.summary.gmeans prints the summary", {
  withr::local_seed(123L)
  cl <- gmeans(as.matrix(iris[, -5L]))
  expect_snapshot(print(summary(cl)))
  expect_invisible(print(summary(cl)))
})
